# Generated by Django 4.1.2 on 2022-10-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='token_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
