# Generated by Django 4.1.2 on 2022-11-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_patientbill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientbill',
            name='prescription',
        ),
    ]
